spring:
    datasource:
        url: jdbc:mysql://localhost:3306/javaquiz
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true

server:
    port: 8080
    error:
        include-message: always
        whitelabel:
            enabled: true

logging:
    level:
        root: info